const TELEGRAM_API_ID = Number(process.env.TELEGRAM_API_ID);
const TELEGRAM_API_HASH = process.env.TELEGRAM_API_HASH!;
const TELEGRAM_SESSION = process.env.TELEGRAM_SESSION!;

export { TELEGRAM_SESSION, TELEGRAM_API_ID, TELEGRAM_API_HASH };
